# Generated by Django 5.2.6 on 2025-10-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['-display_order', 'platform']},
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Higher number displays first'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured projects will be displayed first'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='display_name',
            field=models.CharField(blank=True, help_text='Custom display name (optional)', max_length=50),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Higher number displays first'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='Live Demo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(help_text='Comma-separated list of technologies used', max_length=200),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('website', 'Personal Website')], max_length=20),
        ),
    ]
