# Generated by Django 5.2.7 on 2025-10-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_sociallink_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if currently working here', null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Describe your responsibilities and achievements')),
                ('technologies', models.CharField(help_text='Technologies used (comma-separated)', max_length=300)),
                ('company_url', models.URLField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Higher number displays first')),
            ],
            options={
                'ordering': ['-display_order', '-start_date'],
            },
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('website', 'Personal Website')], max_length=20),
        ),
    ]
